const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('/home/darrell/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const base='http://127.0.0.1:18809',results=[];
(async()=>{const b=await chromium.launch({headless:true,executablePath:'/home/darrell/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});try{for(const version of ['old','final'])for(const dark of [false,true]){
const c=await b.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'}),p=await c.newPage();let revision=0,main='';
await p.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==base||r.request().method()!=='GET')return r.abort();if(u.pathname==='/api/ui-refresh')return r.fulfill({json:{epoch:'one',revision}});if(u.pathname==='/checker-main')return r.fulfill({contentType:'text/html',body:main});if(version==='old'&&u.pathname==='/static/js/page-refresh.js')return r.fulfill({contentType:'text/javascript',body:fs.readFileSync('/tmp/DI5-final-a11y.JYHU8N/web/static/js/page-refresh.js')});return r.continue()});
await p.goto(base+'/dashboard?start=2026-08-01&end=2026-08-28');await p.evaluate(d=>document.documentElement.classList.toggle('dark',d),dark);await p.waitForTimeout(400);main=await p.locator('main').evaluate(e=>e.outerHTML);
await p.locator('#dashboard-date-start').fill('2026-07-01');revision=1;await p.evaluate(()=>dispatchEvent(new Event('focus')));const notice=p.getByRole('region',{name:'Page refresh'});await notice.waitFor();await notice.getByRole('button',{name:'Keep editing'}).focus();await p.evaluate(()=>{window.savedButton=document.activeElement;window.savedRegion=document.querySelector('section[aria-label="Page refresh"]')});
await p.screenshot({path:`checker-evidence/main-focus-${version}-${dark}-before.png`});
await p.evaluate(()=>htmx.ajax('GET','/checker-main',{target:'main',swap:'outerHTML'}));await p.waitForTimeout(100);
const state=await p.evaluate(()=>({active:document.activeElement.tagName,sameButton:document.activeElement===window.savedButton,buttonConnected:window.savedButton.isConnected,sameRegion:window.savedRegion===document.querySelector('section[aria-label="Page refresh"]'),count:document.querySelectorAll('section[aria-label="Page refresh"]').length,insideMain:!!document.activeElement.closest('main'),rect:window.savedButton.getBoundingClientRect().toJSON()}));
await p.screenshot({path:`checker-evidence/main-focus-${version}-${dark}-after.png`});results.push({version,dark,...state});console.log(results.at(-1));await c.close();
}}finally{await b.close();fs.writeFileSync('checker-evidence/main-focus.json',JSON.stringify(results,null,2))}assert(results.filter(x=>x.version==='old').every(x=>x.sameButton),'counterfactual retains focus');assert(results.filter(x=>x.version==='final').every(x=>x.sameButton||x.insideMain),'constitution 10: restore focus after main swap');})().catch(e=>{console.error(e);process.exitCode=1});
