#!/usr/bin/env bash
# accept.sh — executable acceptance oracle for S2 (order-independent,
# globally closest-date auto-pairing in internal/services/transfers).
#
# Run from the root of a worktree. Writes ONE temporary external test file
# into internal/services/transfers/ and removes it on exit. Exit 0 = accept.
#
# The oracle is the contract; it was written before dispatch and neither arm
# may edit it. Any arm that changes accept.sh fails by definition.
set -u

ORACLE_TEST=internal/services/transfers/zz_s2_oracle_test.go
cleanup() { rm -f "$ORACLE_TEST"; }
trap cleanup EXIT

fails=0
step() {                      # step <name> <cmd...>
  local name="$1"; shift
  local out rc
  out=$("$@" 2>&1); rc=$?
  if [[ $rc -eq 0 ]]; then
    echo "PASS  $name"
  else
    echo "FAIL  $name (exit $rc)"
    echo "$out" | tail -40 | sed 's/^/      /'
    fails=$((fails+1))
  fi
}

echo "== S2 oracle =="

step "go build ./..." go build ./...
step "go vet ./..."   go vet ./...

cat > "$ORACLE_TEST" <<'GOTEST'
// Code generated by .swarm/tier3/S2/accept.sh — do not commit.
package transfers_test

import (
	"fmt"
	"sort"
	"strings"
	"testing"
	"time"

	"budget2/internal/models"
	"budget2/internal/services/transfers"
)

func s2Day(day int) time.Time {
	return time.Date(2026, 1, day, 0, 0, 0, 0, time.UTC)
}

// s2Fixture is the review's counterexample plus an unpaired pattern row.
//
//	A  -100.00  Jan 10  chk  pattern hit
//	B  +100.00  Jan 14  sav  no pattern   (far  candidate for A: 4 days)
//	C  +100.00  Jan 11  sav  no pattern   (near candidate for A: 1 day)
//	E  -100.00  Jan 20  chk  pattern hit, no counterparty in window
//
// Correct behaviour: A pairs with C in every input order; B is left alone;
// E is typed external. The pre-fix greedy pass pairs A with whichever of
// B/C the row order lets claim it first.
func s2Fixture() []models.Transaction {
	mk := func(id string, amount float64, day int, acct, desc string) models.Transaction {
		return models.Transaction{
			ID:          id,
			Date:        s2Day(day),
			Amount:      amount,
			Description: desc,
			AccountID:   acct,
			StableID:    fmt.Sprintf("%s|2026-01-%02d|%d|%s", acct, day, models.AmountCents(amount), id),
		}
	}
	return []models.Transaction{
		mk("A", -100.00, 10, "chk", "INTERNAL TRANSFER TO SAVINGS"),
		mk("B", 100.00, 14, "sav", "DEPOSIT"),
		mk("C", 100.00, 11, "sav", "DEPOSIT"),
		mk("E", -100.00, 20, "chk", "INTERNAL TRANSFER TO SAVINGS"),
	}
}

// s2Summary renders a classification as an order-independent string: every
// row keyed by its own ID, plus the review queue.
func s2Summary(r transfers.Result) string {
	rows := make([]string, 0, len(r.Transactions))
	for _, t := range r.Transactions {
		rows = append(rows, fmt.Sprintf("row %s type=%s class=%s pair=%s",
			t.ID, t.TransactionType, t.TransferClass, t.TransferPairKey))
	}
	sort.Strings(rows)
	q := make([]string, 0, len(r.Suspected))
	for _, s := range r.Suspected {
		q = append(q, fmt.Sprintf("queue %s..%s %s", s.Left.ID, s.Right.ID, s.Reason))
	}
	sort.Strings(q)
	return strings.Join(append(rows, q...), "\n") +
		fmt.Sprintf("\npaired=%d external=%d", r.Paired, r.External)
}

func s2Permutations(in []models.Transaction) [][]models.Transaction {
	var out [][]models.Transaction
	var rec func(cur, rest []models.Transaction)
	rec = func(cur, rest []models.Transaction) {
		if len(rest) == 0 {
			cp := make([]models.Transaction, len(cur))
			copy(cp, cur)
			out = append(out, cp)
			return
		}
		for i := range rest {
			nextRest := make([]models.Transaction, 0, len(rest)-1)
			nextRest = append(nextRest, rest[:i]...)
			nextRest = append(nextRest, rest[i+1:]...)
			rec(append(cur, rest[i]), nextRest)
		}
	}
	rec(nil, in)
	return out
}

// TestS2OracleOrderIndependence: every permutation of the same rows must
// classify identically.
func TestS2OracleOrderIndependence(t *testing.T) {
	perms := s2Permutations(s2Fixture())
	if len(perms) != 24 {
		t.Fatalf("fixture produced %d permutations, want 24", len(perms))
	}
	want := s2Summary(transfers.Classify(perms[0], nil, nil))
	for i, p := range perms {
		order := make([]string, 0, len(p))
		for _, tx := range p {
			order = append(order, tx.ID)
		}
		got := s2Summary(transfers.Classify(p, nil, nil))
		if got != want {
			t.Fatalf("input order %v classified differently:\n--- want (order of perm 0) ---\n%s\n--- got (perm %d) ---\n%s",
				order, want, i, got)
		}
	}
}

// TestS2OracleClosestDate: the nearer legs pair, in every input order.
func TestS2OracleClosestDate(t *testing.T) {
	byID := func(r transfers.Result, id string) models.Transaction {
		for _, tx := range r.Transactions {
			if tx.ID == id {
				return tx
			}
		}
		t.Fatalf("row %s missing from result", id)
		return models.Transaction{}
	}
	for _, p := range s2Permutations(s2Fixture()) {
		r := transfers.Classify(p, nil, nil)
		a, b, c, e := byID(r, "A"), byID(r, "B"), byID(r, "C"), byID(r, "E")
		if a.TransferClass != transfers.ClassPaired || c.TransferClass != transfers.ClassPaired {
			t.Fatalf("A and C must pair (1 day apart); got A=%q C=%q", a.TransferClass, c.TransferClass)
		}
		if a.TransferPairKey == "" || a.TransferPairKey != c.TransferPairKey {
			t.Fatalf("A and C must share a pair key; got %q and %q", a.TransferPairKey, c.TransferPairKey)
		}
		if b.TransferClass == transfers.ClassPaired {
			t.Fatalf("B (4 days away) must not consume A's nearer counterparty")
		}
		if e.TransferClass != transfers.ClassExternal {
			t.Fatalf("E is a pattern hit with no counterparty; want external, got %q", e.TransferClass)
		}
	}
}

// TestS2OracleNoRowDropped: classification never loses or duplicates a row.
func TestS2OracleNoRowDropped(t *testing.T) {
	for _, p := range s2Permutations(s2Fixture()) {
		r := transfers.Classify(p, nil, nil)
		if len(r.Transactions) != len(p) {
			t.Fatalf("Classify returned %d rows for %d inputs", len(r.Transactions), len(p))
		}
		seen := map[string]int{}
		for _, tx := range r.Transactions {
			seen[tx.ID]++
		}
		for _, id := range []string{"A", "B", "C", "E"} {
			if seen[id] != 1 {
				t.Fatalf("row %s appears %d times, want 1", id, seen[id])
			}
		}
		if r.Paired+r.External != r.Classified() {
			t.Fatalf("Paired+External != Classified()")
		}
	}
}
GOTEST

step "oracle: order independence / closest date / no drop" \
  go test -count=1 -run 'TestS2Oracle' ./internal/services/transfers/
step "transfers package tests"  go test -count=1 ./internal/services/transfers/...
step "dataloader package tests" go test -count=1 ./internal/services/dataloader/...
step "full suite"               go test -count=1 ./...

cleanup
if [[ $fails -eq 0 ]]; then
  echo "ORACLE: PASS"
  exit 0
fi
echo "ORACLE: FAIL ($fails check(s))"
exit 1
