#!/usr/bin/env bash
# Generates docs/api/README.md — an index of the gomarkdoc-generated package docs.
# Invoked by `make docs-api` after gomarkdoc runs.

set -euo pipefail

cd "$(dirname "$0")/.."

API_DIR="docs/api"
if [ ! -d "$API_DIR" ]; then
    echo "$API_DIR not found. Run gomarkdoc first."
    exit 1
fi

# Extracts the package overview paragraph (between the import block and the first ## heading).
extract_synopsis() {
    awk '
        BEGIN { in_import=0; after_import=0; buf=""; }
        /^```go$/ && !after_import { in_import=1; next }
        /^```$/ && in_import { in_import=0; after_import=1; next }
        in_import { next }
        after_import && /^## / { exit }
        after_import {
            sub(/^[ \t]+/, ""); sub(/[ \t]+$/, "");
            if ($0 == "") {
                if (buf != "" && buf !~ / \/ $/) buf = buf " / "
            } else {
                buf = buf $0 " "
            }
        }
        END {
            sub(/ \/ $/, "", buf); sub(/ +$/, "", buf); print buf
        }
    ' "$1"
}

# First sentence only, for the table cell.
first_sentence() {
    local s="$1"
    s=$(echo "$s" | sed 's/ \/ .*//')
    s=$(echo "$s" | sed 's/\([^.]*[.]\) .*/\1/')
    if [ -z "$s" ]; then echo "_(no package doc)_"; else echo "$s"; fi
}

row_for() {
    local f="$1"
    local pkg rel syn
    pkg=$(grep -m1 '^import "' "$f" | sed 's/.*"\(.*\)".*/\1/')
    rel=${f#${API_DIR}/}
    syn=$(first_sentence "$(extract_synopsis "$f")")
    printf '| [`%s`](%s) | %s |\n' "$pkg" "$rel" "$syn"
}

{
    cat <<'EOF'
# Go Package API Reference

Generated by [gomarkdoc](https://github.com/princjef/gomarkdoc) from Go doc comments. Regenerate with `make docs-api`.

Each page links back to source on GitHub for the symbol-level definition.

## Commands

| Package | Synopsis |
|---------|----------|
EOF

    find "$API_DIR/cmd" -name "*.md" 2>/dev/null | sort | while read -r f; do row_for "$f"; done

    cat <<'EOF'

## Internal Packages

| Package | Synopsis |
|---------|----------|
EOF

    find "$API_DIR/internal" -name "*.md" 2>/dev/null | sort | while read -r f; do row_for "$f"; done
} > "$API_DIR/README.md"

echo "Wrote $API_DIR/README.md"
